### ISSUE TITLE
subnets without vlanid 

### ISSUE THREAD

**Issue by Soras2919** [HanseMerkur/terraform-provider-foreman#20]
Terraform wants to change a subnet everytime I run apply when the "vlanid" attribute is omitted. I also set it to null with same result.

**Comment by mgusek-interhyp** [comment]
The error is known, I am working on it

**Comment by mgusek-interhyp** [comment]
For clarification: Can you run in Debug-Mode and post the output ?

**Comment by Soras2919** [comment]
Not sure if the debug log helps, cause there appears no errors at all. It just seems vlanid can't be null and if you set it to null foreman somehow reapplies sth.
When calling apply or plan the output of terraform is:
**vlanid          = "%!f(\<nil\>)" -> null**
Probably this helps.
Hope linking the log file works as expected?
[terraform-provider-foreman.log](https://github.com/HanseMerkur/terraform-provider-foreman/files/6140652/terraform-provider-foreman.log)

**Comment by mgusek-interhyp** [comment]
With https://github.com/HanseMerkur/terraform-provider-foreman/pull/21 i address this problem. After merging and creating a new version you may fix your terraform.tfstate from "vlanid": "%!f(<nil>)" to "vlanid": 0 or remove this entire line. With next run of terraform, you should have an clean file
