### ISSUE TITLE
Move API calls to a library of its own

### ISSUE THREAD

**Issue by lhw** [HanseMerkur/terraform-provider-foreman#4]
With a few modifications its possible to extract a [swagger api definition](https://github.com/HanseMerkur/terraform-provider-foreman/blob/swagger/swagger_api_definition.json) from foreman. This would be a great base for a golang foreman api library. Which in turn could be used here.

**Comment by adarobin** [comment]
I started doing this for Satellite at https://github.com/umich-vci/gosatellite using go-swagger. The problem I ran into is that the API does not document any of its responses which makes the generated client useless.

**Comment by adarobin** [comment]
I put in an RFE - https://bugzilla.redhat.com/show_bug.cgi?id=1803138

**Comment by lhw** [comment]
I did some tests initially with go-swagger and pyswagger and as you described only ended up with unusable gibberish. The whole foreman/satellite API is a bit of a mess. It also reacts returns results in an unpredictable manner on some endpoints.
The swagger variant was an idea I had. But generally it could be useful to abstract the API out of the project so it could be used elsewhere.
