### ISSUE TITLE
Add managed parameter for host creation

### ISSUE THREAD

**Issue by m-garrido** [HanseMerkur/terraform-provider-foreman#52]
Hello,

I would like to created an "unmanaged" host within foreman.
I can do that by API with this json data : `'{"host": {"managed": false, "name": "sample-vm"}'`
But, i didn't find the way to set the managed parameter within "foreman_host".
Is there a way to create a unmanaged host ? If not, please, can you add this feature ?

Thanks in advance.

**Comment by agriffit79** [comment]
I recently added a parameter called `manage_build` but the documentation has not been updated to reflect it. Can you try setting this to false (it defaults to true) and see if that works for you?

**Comment by lhw** [comment]
Yes. The `manage_build` parameter should reflect the change you want to see. Maybe we need to adjust the documentation to include some key words so people can find it easier.

**Comment by agriffit79** [comment]
The documentation on the terraform website is out of date. It does not mention the new parameter. I think it needs updating since #48

**Comment by lhw** [comment]
Yes. Automating the docs auto-regeneration is a bit of a hassle as the hashicorp registry only checks the same branch docs/ directory. So it would have to be a git hook most likely.
