### ISSUE TITLE
Can't set host parameters

### ISSUE THREAD

**Issue by holmesb** [HanseMerkur/terraform-provider-foreman#66]
Some bug was introduced in last week's [refactor host and add managed fields](https://github.com/HanseMerkur/terraform-provider-foreman/commit/7c4c90b9019e8bcf86efe78a62b592a44b3475f2) commit. Can no longer set host parameters, ie:

```
resource "foreman_host" "example" {
  name = "host01"
  parameters = {
    test_param = "test_value"
  }
}
```
test_param never appears in Host Parameters.
![image](https://user-images.githubusercontent.com/5072156/167726573-fb4e022b-f61f-4969-bc33-dff0f362c31c.png)

Probably interests @MrFreezeex 
Let me know if you need a fuller example. If you build the prior commit (7be9a216) on 26/4, params are created fine.

**Comment by MrFreezeex** [comment]
Thanks, will look into it.
