### ISSUE TITLE
Add support to organization_id and location_id

### ISSUE THREAD

**Issue by galindro** [HanseMerkur/terraform-provider-foreman#7]
Hi,
We need to define organization_id and location_id during the host creation but it seems that this provider doesn't supports it. Is it something very hard to implement?

**Comment by lhw** [comment]
It's actually the one feature blocking this provider from working with foreman 1.21 and newer as they are now mandatory parameters. My idea was to add the org and loc id to the provider configuration and re-use it for all resources with an optional override in each datasource/resource.

All in all it's a larger change but nothing ground breaking. I have the intention to fix this in near future.
